gui:
  theme:
    activeBorderColor:
      - "#9580ff"
      - bold
    inactiveBorderColor:
      - "#424450"
    optionsTextColor:
      - "#80ffea"
    selectedLineBgColor:
      - "#2e2b3b"
    cherryPickedCommitBgColor:
      - "#393649"
    cherryPickedCommitFgColor:
      - "#9580ff"
    unstagedChangesColor:
      - "#ff9580"
    defaultFgColor:
      - "#f8f8f2"
    searchingActiveBorderColor:
      - "#ffca80"

  authorColors:
    "*": "#7970a9"
