################################################
#                                              #
# ████████╗██╗  ██╗███████╗███╗   ███╗███████╗ #
# ╚══██╔══╝██║  ██║██╔════╝████╗ ████║██╔════╝ #
#    ██║   ███████║█████╗  ██╔████╔██║█████╗   #
#    ██║   ██╔══██║██╔══╝  ██║╚██╔╝██║██╔══╝   #
#    ██║   ██║  ██║███████╗██║ ╚═╝ ██║███████╗ #
#    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝ #
#                                              #
################################################

[manager]
syntect_theme = "~/.config/yazi/Dracula Pro.tmTheme"
