#!/bin/bash

# Slimmed down version of my play function for Fish shell converted to Bash
function play {
	# Check for existing MPV instance using mpv.sock
	if [[ -e /tmp/mpv.sock && $(echo "{\"command\": [\"get_version\"]}" | socat - /tmp/mpv.sock | grep "success") ]]; then
		echo "raw loadfile $@ append" | socat - /tmp/mpv.sock
	fi

	# Kill any rogue MPV processes
	pkill mpv

	# Create MPV instance
	nohup mpv --no-terminal --input-ipc-server=/tmp/mpv.sock $@ &> /dev/null &disown
}

play "$1"
